import Head from 'next/head'
import Navbar from "./Navbar";
import Footer from "./Footer";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet"/>
                <style>{`
                    body {
                        font-family: "Poppins" !important;
                    }
                    .rounded-x {
                        border-radius: 10px;
                    }

                    .rounded-x-7 {
                        border-radius: 15px !important;
                    }
                `}</style>
            </Head>
            <Navbar/>
            <main className="gap-0 mt-0 mb-5 d-flex flex-column">{children}</main>
            <Footer/>
        </>
    )
}

export default Layout;