import Head from 'next/head'
import Navbar from "./Navbar";
import Footer from "./Footer";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
            </Head>
            <Navbar/>
            <main className="gap-0 mt-0 mb-5 d-flex flex-column">{children}</main>
            <Footer/>
        </>
    )
}

export default Layout;