import Head from 'next/head'
import Image from 'next/image'
import Economics from '../components/Economics'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Parallax from '../components/Parallax'
import Roostr from '../components/Roostr'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Navbar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
      </Head>

      <main className="gap-0 mt-0 mb-5 d-flex flex-column">
        <Parallax/>
        <Roostr/>
        <Economics/>
        <Footer/>
      </main>
    </div>
  )
}
